package com.hstairs.ppmajal.pddl.heuristics.advanced;

import com.hstairs.ppmajal.PDDLProblem.PDDLProblem;
import com.hstairs.ppmajal.conditions.*;
import com.hstairs.ppmajal.problem.State;
import it.unimi.dsi.fastutil.ints.IntArrayFIFOQueue;
import it.unimi.dsi.fastutil.ints.IntArrayList;
import it.unimi.dsi.fastutil.ints.IntArraySet;
import it.unimi.dsi.fastutil.ints.IntSet;
import org.jgrapht.alg.util.Pair;
import org.jgrapht.util.FibonacciHeap;
import org.jgrapht.util.FibonacciHeapNode;

import java.util.*;

public class LmCut extends H1 {

    private final int NOBEST = -1;
    protected final int root;
    protected final int[] pcf;
    protected final IntArraySet[] pcf2Actions;
    protected float[] reducedCosts;
    protected float minCostAction;

    record Cut(int act, int cond) {
    }
    record JGraph(Collection<Integer> V, IntArrayList[][] E, Collection<Integer>[] ERev) {
    }

    public LmCut(PDDLProblem problem, boolean additive, boolean extractRelaxedPlan, boolean maxHelpfulTransitions,
                 String redConstraints, boolean helpfulActionsComputation, boolean reachability,
                 boolean helpfulTransitions, boolean conjunctionsMax, boolean unitaryCost,
                 int linearEffectsAbstraction) {
        this(problem, additive, extractRelaxedPlan, maxHelpfulTransitions, redConstraints,
                helpfulActionsComputation, reachability, helpfulTransitions, conjunctionsMax,
                null, unitaryCost, linearEffectsAbstraction, false);
    }

    protected LmCut(PDDLProblem problem, boolean additive, boolean extractRelaxedPlan, boolean maxHelpfulTransitions,
                  String redConstraints, boolean helpfulActionsComputation, boolean reachability,
                  boolean helpfulTransitions, boolean conjunctionsMax, Map<AndCond, Collection<IntArraySet>> redundantMap,
                  boolean unitaryCost, int compNumericStrategy, boolean ssnpAwareVersion) {
        super(problem, additive, extractRelaxedPlan, maxHelpfulTransitions, redConstraints,
                helpfulActionsComputation, reachability, helpfulTransitions, conjunctionsMax,
                redundantMap, unitaryCost, compNumericStrategy, ssnpAwareVersion);
        this.root = getTotNumberOfTerms();
        this.pcf = new int[cp.numActions()];
        Arrays.fill(this.pcf, -1);
        pcf2Actions = new IntArraySet[getTotNumberOfTerms()+1];
        minCostAction = Float.POSITIVE_INFINITY;
    }

    Float updateJG(JGraph jg, State gs, Collection<Cut> cuts) {

        final FibonacciHeap heap = new FibonacciHeap();
        Arrays.fill(getClosed(), false);
        nodeOf = new FibonacciHeapNode[cp.numActions()];
        final ArrayList<Cut> toExplore = new ArrayList<>();
        for (Cut cut : cuts) {
//            System.out.println("pcf: "+ pcf[cut.act]+ "root:"+root);
            if (jg.E[pcf[cut.act]][cut.act] != null) { // This shouldn't happen. There are cuts which are generated by reversed edged which are outdated.
                for (var v : jg.E[pcf[cut.act]][cut.act]) {
                    toExplore.add(new Cut(cut.act, v));
                }
            }
        }
        for (final Cut cut : toExplore) {
            final int v = cut.cond;
            final float supporterCost = getActionCost()[cut.act] == 0f
                    ? actionHCost[cut.act]
                    : computeSupporterCost(v, cut.act, gs,true);
            if (updateIfNeeded(v, supporterCost)) {
                updateActions(v, heap);
            }
        }

        while (!heap.isEmpty()) {
            final int actionId = (int) heap.removeMin().getData();
            jg.V.add(pcf[actionId]);
            jg.E[pcf[actionId]][actionId] = new IntArrayList();
            closed[actionId] = true;
            if (actionId != cp.goal()) {
                final IntSet conditionsAchievableByAction = getConditionsAchievableById(actionId);
                for (final int conditionId : conditionsAchievableByAction) {
                    if (!getConditionInit()[conditionId]) {
                        addConditionToEdges(jg.E,pcf[actionId],actionId,conditionId);
                        //jg.ERev[actionId].add(conditionId);
                        final float supporterCost = getActionCost()[actionId] == 0f
                                ? actionHCost[actionId]
                                : computeSupporterCost(conditionId, actionId, gs,true);
                        if (updateIfNeeded(conditionId, supporterCost)) {
                            updateActions(conditionId, heap);
                        }
                    }
                }
            } else if (getActionHCost()[actionId] == 0f) {
                break;
            }

        }
        return getActionHCost()[cp.goal()];
    }

    Pair<JGraph, Float> constructJG(State gs) {
        final IntArrayList vertices = new IntArrayList();
        final IntArrayList[][] edges = new IntArrayList[getTotNumberOfTerms() + 1][allActions.size()+1];
        final IntArrayList[] reverseEdges = new IntArrayList[getTotNumberOfTerms() + 1];
        vertices.add(root);
        reverseEdges[root] = new IntArrayList();

        Arrays.fill(getActionHCost(), Float.MAX_VALUE);
        Arrays.fill(getConditionCost(), Float.MAX_VALUE);
        Arrays.fill(getClosed(), false);
        Arrays.fill(getConditionInit(), false);
        Arrays.fill(pcf, -1);
        allAchievers = new IntArraySet[getTotNumberOfTerms()];

        final FibonacciHeap heap = new FibonacciHeap();
        for (final int conditionId : allConditions) {
            if (gs.satisfy(Terminal.getTerminal(conditionId))) {
                conditionCost[conditionId] = 0f;
                conditionInit[conditionId] = true;
            }
            updateActions(conditionId, heap);
        }
        for (final int conditionId : getAllConditions()) {
            vertices.add(conditionId);
            reverseEdges[conditionId] = new IntArrayList();
        }

        for (final int freePreconditionAction : freePreconditionActions) {
            getActionHCost()[freePreconditionAction] = 0f;
            addActionsInPriority(freePreconditionAction, heap, 0f);
            vertices.add(root);
            setPCF(root, freePreconditionAction);
        }

//        for (final int actionId : allActions) {
//            final Condition condition = cp.preconditionFunction()[actionId];
//            if (gs.satisfy(condition) && !getActionInit()[actionId]) {
//                addActionsInPriority(actionId, heap, 0f);
//                getActionHCost()[actionId] = 0f;
//                setPCF(root,actionId);
//            }
//        }

        while (!heap.isEmpty()) {
            final int actionId = (int) heap.removeMin().getData();
            if (!getClosed()[actionId]) {
                getClosed()[actionId] = true;
                vertices.add(pcf[actionId]);
                nodeOf[actionId] = null;
                if (actionId != cp.goal()) {
                    final IntSet conditionsAchievableByAction = getConditionsAchievableById(actionId);
                    for (final int conditionId : conditionsAchievableByAction) {
                        if (!getConditionInit()[conditionId]) {
                            addConditionToEdges(edges, pcf[actionId], actionId, conditionId);
                            reverseEdges[conditionId].add(actionId);
                            final float supporterCost = getActionCost()[actionId] == 0f
                                    ? actionHCost[actionId]
                                    : computeSupporterCost(conditionId, actionId, gs, true);
                            if (updateIfNeeded(conditionId, supporterCost)) {
                                updateActions(conditionId, heap);
                            }
                        }
                    }
                } else if (getActionHCost()[actionId] == 0f) {
                    break;
                }
            }
        }
        return Pair.of(new JGraph(vertices, edges, reverseEdges), getActionHCost()[cp.goal()]);
    }

    private void setPCF(int root, int actionId) {
        pcf[actionId] = root;
        if (pcf2Actions[root] == null){
            pcf2Actions[root] = new IntArraySet();
        }
        pcf2Actions[root].add(actionId);
    }

    private void addConditionToEdges(IntArrayList[][] edges, int i, int actionId, int conditionId) {
        if (edges[i][actionId] == null) {
            edges[i][actionId] = new IntArrayList();
        }
        edges[i][actionId].add(conditionId);

    }

    @Override
    protected void updateActions(final int conditionId, final FibonacciHeap heap) {
        final IntArraySet actions = getConditionToAction()[conditionId];
        if (actions != null) {
            for (final int actionId : actions) {
                if (!closed[actionId]) {
                    final Pair<Float, Integer> justifier = estimateCostLMCUT(cp.preconditionFunction()[actionId], actionHCost[actionId]);
                    final float value = justifier.getFirst();
                    if (value < Float.MAX_VALUE && !getActionInit()[actionId]) {
                        if (value < getActionHCost()[actionId]) {
                            if (getActionHCost()[actionId] == Float.MAX_VALUE) {
                                getActionHCost()[actionId] = value;
                                addActionsInPriority(actionId, heap, value);
                            } else {
                                getActionHCost()[actionId] = value;
                                if (getNodeOf()[actionId] == null){
                                    addActionsInPriority(actionId, heap, value);
                                }else {
                                    heap.decreaseKey(getNodeOf()[actionId], value);
                                }
                            }
                        }
                        if (justifier.getSecond() == NOBEST) {
                            if (pcf[actionId] == -1) {
                                setPCF(root, actionId);
                            }
                        }else{
                            if (pcf[actionId] != justifier.getSecond()) {
                                if (pcf[actionId] != -1){
                                    pcf2Actions[pcf[actionId]].remove(actionId);
                                }
                                setPCF(justifier.getSecond(), actionId);
                            }
                        }
                    }
                }
            }

        }
    }

    @Override
    public float computeEstimate(State gs) {
        float cost = 0f;
        boolean firstTime = true;
        reducedCosts = Arrays.copyOf(cp.actionCost(), cp.actionCost().length);
        JGraph justificationGraph = null;
        while (true) {
            final boolean[] goalZone = new boolean[getTotNumberOfTerms() + 1];

            if (firstTime) {
                final Pair<JGraph, Float> jGraphAndValue = constructJG(gs);
                justificationGraph = jGraphAndValue.getFirst();
                final float goalValue = jGraphAndValue.getSecond();

                if (goalValue == 0f || goalValue == Float.MAX_VALUE) {
                    return firstTime ? goalValue : cost;
                }
            }

            firstTime = false;

            markGoalZone(justificationGraph, pcf[cp.goal()], goalZone, new IntArraySet());
            final Collection<Cut> cuts = computeCuts(justificationGraph, goalZone);
            if (cuts.isEmpty()) {
                return cost;
            }

            float min = Float.POSITIVE_INFINITY;
            final float[] actionOut = new float[cp.numActions()];
            Arrays.fill(actionOut, Float.POSITIVE_INFINITY);
            for (final var cut : cuts) {
                final float supporterCost = computeSupporterCost(cut.cond, cut.act, gs,false);
                if (supporterCost < min) {
                    min = supporterCost;
                }
                actionOut[cut.act] = Math.min(actionOut[cut.act], supporterCost/getActionCost()[cut.act]);
            }

            if (min <= 0.00001f) {
                return cost;
            }
            for (final var cut : cuts) {
                getActionCost()[cut.act] -= min / actionOut[cut.act];
            }
            cost += min;
            if (true){
                Float res = updateJG(justificationGraph,gs,cuts);
                if (res == 0f){
                    return cost;
                }
            }else{
                final Pair<JGraph, Float> jGraphAndValue = constructJG(gs);
                justificationGraph = constructJG(gs).getFirst();
                if (jGraphAndValue.getSecond() == 0f){
                    return cost;
                }
            }
        }
    }

    @Override
    public float[] getActionCost() {
        return reducedCosts;
    }

    private void markGoalZone(JGraph graph, int starting, boolean[] goalZone, IntArraySet seen) {
        goalZone[starting] = true;
        if (seen.contains(starting)) {
            return;
        }else{
            seen.add(starting);
        }
        for (final int actionId : graph.ERev[starting]) {
            if (getActionCost()[actionId] <= 0f) {
                markGoalZone(graph, pcf[actionId], goalZone,seen);
            }
        }
    }

    private Collection<Cut> computeCuts(JGraph graph, boolean[] goalZone) {
        final Collection<Cut> cuts = new ArrayList<>();
        final IntArrayFIFOQueue queue = new IntArrayFIFOQueue();
        boolean closedCondition[] = new boolean[totNumberOfTerms+1];
        queue.enqueue(root);
        while (!queue.isEmpty()) {
            final int current = queue.dequeueInt();
            closedCondition[current] = true;
            if (pcf2Actions[current] != null) {
                for (var act : pcf2Actions[current]) {
                    if (graph.E[current][act] != null) {
                        for (var cond : graph.E[current][act]) {
                            if (goalZone[cond]) {
                                cuts.add(new Cut(act, cond));
                            } else if (!closedCondition[cond]) {
                                queue.enqueue(cond);
                            }
                        }
                    }
                }
            }
        }
        return cuts;
    }

    private Pair<Float, Integer> estimateCostLMCUT(final Condition c, float previous) {
        if (c instanceof AndCond and) {
            if (and.sons == null) {
                return Pair.of(0f, null);
            }
            float ret = 0f;
            int best = NOBEST;
            for (final var son : and.sons) {
                final Pair<Float, Integer> child = estimateCostLMCUT((Condition) son, previous);
                if (child.getFirst() == Float.MAX_VALUE) {
                    return Pair.of(Float.MAX_VALUE, NOBEST);
                }
                if (ret < child.getFirst()) {
                    ret = child.getFirst();
                    best = child.getSecond();
                }
            }
            return Pair.of(ret, best);
        } else if (c instanceof OrCond or) {
            if (or.sons == null) {
                return Pair.of(0f, NOBEST);
            }
            float ret = Float.POSITIVE_INFINITY;
            int best = NOBEST;
            for (final var son : or.sons) {
                final Pair<Float, Integer> child = estimateCostLMCUT((Condition) son, previous);
                if (ret > child.getFirst()) {
                    ret = child.getFirst();
                    best = child.getSecond();
                    if (ret == 0f){
                        return  Pair.of(0f, NOBEST);
                    }
                }
            }
            return Pair.of(ret, best);
        } else if (c instanceof Terminal t) {
            return Pair.of(getConditionCost()[t.getId()], t.getId());
        }
        throw new RuntimeException("This is not supported:" + c);
    }

    private float computeSupporterCost(int conditionId, int actionId, State gs, boolean includeHeuristicCost) {
        final Terminal terminal = Terminal.getTerminal(conditionId);
        float actionCost = getActionCost()[actionId];
        final float heuristicCost = includeHeuristicCost ? getActionHCost()[actionId] : 0f;

        if (!(terminal instanceof Comparison comparison)) {
            return heuristicCost + actionCost;
        }

        final float contribution = numericContribution(actionId, comparison);
        if (contribution <= 0f) {
            return -1f;
        }

        final float repetitions = computeRepetitions(comparison, contribution, gs);
        if (contribution == UNKNOWNEFFECT)
            actionCost = 0f;
        return heuristicCost + repetitions * actionCost;
    }

    protected float computeRepetitions(Comparison comparison, float contribution, State state) {
        final double eval = comparison.getLeft().eval(state);
        if (Double.isNaN(eval) || contribution == UNKNOWNEFFECT) {
            return 1f;
        }
        final float repetitions = (float) (-eval / contribution);
        return comparison.isStrict && isAdditive()
                ? repetitions + Float.MIN_VALUE
                : repetitions;
    }

    private float getMinCostAction() {
        if (minCostAction == Float.POSITIVE_INFINITY){
            for (var v: allActions){
                minCostAction = Math.min(minCostAction, getActionCost()[v]);
            }
        }
        return minCostAction;
    }
}
