(define (problem mprime-x-14)
   (:domain mystery-prime-typed)
   (:objects pea chocolate lobster potato hotdog baguette wurst
             bacon scallion yogurt shrimp flounder papaya cod scallop
             lettuce lemon ham pistachio mutton cucumber - food
             triumph curiosity excitement achievement learning rest
             intoxication love aesthetics - pleasure
             laceration hangover grief sciatica dread loneliness abrasion
             jealousy anger angina anxiety depression anger_1 laceration_2
             prostatitis boils anxiety_3 prostatitis_4 grief_6 depression_7
             jealousy_8 sciatica_15 dread_16 abrasion_5 angina_12 boils_13
             loneliness_14 jealousy_32 grief_9 anger_10 hangover_11 sciatica_28
             boils_29 angina_30 depression_31 laceration_26 hangover_27
             prostatitis_23 loneliness_24 anxiety_25 dread_22 grief_19 angina_20
             abrasion_21 - pain
)
   (:init
(= (harmony love) 2)
(= (harmony rest) 2)
          (craves sciatica_15 shrimp)
(= (locale shrimp) 3)
          (craves depression_7 yogurt)
          (eats bacon scallion)
(= (locale cod) 1)
          (eats pea hotdog)
(= (locale scallop) 5)
          (eats lemon cucumber)
(= (harmony excitement) 3)
          (eats hotdog pea)
          (craves aesthetics cucumber)
          (craves jealousy potato)
          (eats flounder yogurt)
          (craves boils bacon)
          (eats papaya cod)
          (craves laceration_2 bacon)
          (craves grief_6 yogurt)
(= (locale papaya) 3)
          (eats hotdog lobster)
          (eats chocolate wurst)

(= (locale baguette) 5)
(= (locale potato) 2)
          (eats yogurt shrimp)
          (craves angina_30 lettuce)
          (eats scallion shrimp)
          (eats papaya scallion)
(= (locale lobster) 5)
(= (locale chocolate) 2)
(= (harmony intoxication) 3)
          (eats lettuce pistachio)

          (craves anxiety_3 scallion)
          (craves intoxication ham)
          (craves laceration pea)
          (craves rest scallop)
          (eats mutton cucumber)

          (craves loneliness_14 flounder)
          (craves depression wurst)
          (eats shrimp scallion)
          (craves anxiety hotdog)
          (eats bacon yogurt)
          (craves anger_1 bacon)
          (craves loneliness_24 pistachio)
          (eats cod shrimp)
          (craves laceration_26 ham)

          (eats pistachio lettuce)
          (craves triumph pea)
          (craves grief_19 cucumber)
(= (locale wurst) 1)
          (eats shrimp potato)
(= (harmony achievement) 2)
          (craves abrasion_5 shrimp)
          (eats scallop lettuce)
          (craves sciatica chocolate)
          (eats potato pea)
          (craves hangover_27 ham)
          (eats lemon scallop)
          (craves abrasion lobster)
          (craves anger_10 papaya)
          (eats lettuce mutton)
          (eats baguette chocolate)
          (eats scallion scallop)
          (eats ham cucumber)
          (craves love mutton)
(= (locale flounder) 2)
          (craves dread_16 shrimp)
          (eats scallion papaya)
          (craves dread lobster)
          (craves prostatitis_4 scallion)
          (eats scallop baguette)
          (craves curiosity chocolate)
          (eats potato wurst)
          (eats scallop lemon)
          (eats yogurt bacon)
          (eats yogurt flounder)
(= (harmony triumph) 1)
(= (locale mutton) 0)
          (eats shrimp yogurt)
          (craves boils_13 flounder)
          (craves prostatitis bacon)
          (eats scallion bacon)
(= (locale yogurt) 3)
          (craves angina_12 flounder)
          (craves jealousy_8 yogurt)
          (craves loneliness lobster)

(= (locale bacon) 1)
          (craves grief_9 papaya)
          (craves grief chocolate)
          (craves angina potato)
          (eats mutton pistachio)
          (eats lemon ham)
          (eats mutton lettuce)

          (eats scallop scallion)
(= (locale lemon) 2)
          (craves angina_20 cucumber)

(= (locale hotdog) 5)
          (eats mutton lemon)
          (craves boils_29 lettuce)
          (craves hangover chocolate)
          (eats flounder scallion)
(= (locale cucumber) 2)
          (eats wurst potato)
(= (harmony curiosity) 2)
(= (locale pea) 4)
          (eats lettuce scallop)
          (craves jealousy_32 papaya)
          (eats lemon mutton)
          (craves sciatica_28 lettuce)
          (eats lobster baguette)
          (eats potato shrimp)
          (craves abrasion_21 cucumber)
          (eats baguette scallop)
(= (locale lettuce) 2)
          (eats ham lemon)
          (eats shrimp cod)
          (craves learning yogurt)
          (eats baguette lobster)
(= (locale ham) 5)
          (eats scallion flounder)
          (eats cucumber mutton)
          (eats pea potato)
(= (harmony aesthetics) 3)
(= (harmony learning) 3)
          (eats cucumber ham)

          (craves anxiety_25 pistachio)
          (eats lobster hotdog)
          (eats wurst chocolate)
          (craves hangover_11 papaya)
(= (locale pistachio) 1)
          (craves achievement potato)
          (eats chocolate baguette)
          (craves anger potato)
          (craves prostatitis_23 pistachio)
          (craves depression_31 lettuce)
          (eats cod papaya)
          (eats pistachio mutton)
          (eats cucumber lemon)
          (craves excitement lobster)
(= (locale scallion) 3)
          (craves dread_22 mutton))
   (:goal (and (craves prostatitis_23 potato)
               (craves anxiety_25 potato))))
