(define (problem mprime-x-24)
   (:domain mystery-prime-typed)
   (:objects turkey cherry tofu lettuce bacon chicken muffin
             chocolate pepper shrimp orange apple wurst potato melon - food
             achievement satiety curiosity - pleasure
             grief angina depression sciatica loneliness jealousy
             anxiety boils dread hangover laceration prostatitis abrasion
             anger abrasion_2 jealousy_8 prostatitis_3 anxiety_4
             loneliness_1 angina_16 boils_5 dread_6 laceration_7 hangover_13
             depression_14 grief_15 sciatica_11 anger_12 angina_32 anger_9
             hangover_10 loneliness_31 anxiety_26 abrasion_27 dread_28
             sciatica_29 depression_30 - pain
)
   (:init
(= (harmony satiety) 2)
          (craves anger_9 wurst)
          (eats potato wurst)
          (craves curiosity muffin)
          (craves abrasion_27 melon)
          (craves laceration_7 shrimp)
          (eats lettuce bacon)
          (eats melon potato)
          (eats muffin tofu)
          (eats turkey bacon)


(= (locale shrimp) 1)
          (eats orange shrimp)
          (eats cherry chicken)
(= (locale tofu) 0)
(= (harmony curiosity) 3)
          (eats shrimp apple)

          (craves satiety bacon)
(= (locale lettuce) 4)
          (eats pepper potato)

          (craves hangover chicken)
          (eats wurst potato)
          (craves anger muffin)

          (eats apple shrimp)
          (craves depression_30 melon)
          (eats chocolate apple)
          (eats cherry tofu)
          (craves abrasion chicken)

          (craves boils lettuce)
          (eats tofu muffin)
(= (harmony achievement) 2)
          (craves jealousy_8 pepper)
          (craves grief turkey)
(= (locale chocolate) 4)
(= (locale chicken) 2)
          (craves dread lettuce)
(= (locale apple) 0)
          (craves sciatica_11 apple)
          (craves achievement cherry)
          (craves depression cherry)
          (craves dread_28 melon)
          (eats potato pepper)
(= (locale muffin) 3)

          (eats apple chocolate)
          (craves jealousy lettuce)
          (craves boils_5 shrimp)
          (craves anxiety lettuce)
          (craves anxiety_4 pepper)
          (eats wurst orange)
          (eats turkey chicken)
          (craves angina turkey)
          (eats tofu chicken)
          (eats muffin melon)
(= (locale wurst) 1)
          (eats potato melon)
          (eats chocolate pepper)
          (eats cherry lettuce)
(= (locale potato) 9)
          (eats pepper melon)
          (eats melon pepper)
(= (locale orange) 3)
          (craves anger_12 apple)
          (eats chicken tofu)
          (eats orange wurst)
          (eats muffin apple)
          (craves laceration chicken)

(= (locale melon) 9)
          (eats shrimp orange)
(= (locale bacon) 5)
          (eats melon muffin)
          (eats apple muffin)
          (craves hangover_10 wurst)
          (craves grief_15 orange)
          (eats chicken turkey)


          (craves loneliness tofu)
          (craves loneliness_31 potato)
          (craves sciatica_29 melon)
          (craves prostatitis_3 pepper)
(= (locale turkey) 2)
(= (locale pepper) 9)
          (craves hangover_13 orange)
          (craves abrasion_2 chocolate)
          (craves sciatica tofu)
          (craves depression_14 orange)
          (eats pepper chocolate)
          (eats lettuce cherry)
          (eats bacon lettuce)

(= (locale cherry) 0)
          (craves dread_6 shrimp)
          (craves angina_32 wurst)
          (craves angina_16 shrimp)

          (craves anxiety_26 melon)
          (eats bacon turkey)
          (craves prostatitis chicken)
          (eats tofu cherry)
          (eats chicken cherry)
          (craves loneliness_1 pepper))
   (:goal (and (craves jealousy_8 pepper)
               (craves anxiety_4 pepper)
               (craves anger_12 cherry))))
