(define (problem mprime-x-21)
   (:domain mystery-prime-typed)
   (:objects apple muffin lemon flounder wurst okra snickers onion
             marzipan popover hamburger guava - food
             triumph satisfaction learning love expectation rest
             - pleasure
             laceration boils anxiety dread abrasion jealousy prostatitis
             grief hangover depression angina anger grief_2 sciatica
             loneliness depression_8 hangover_3 anger_4 angina_1
             prostatitis_7 abrasion_6 loneliness_15 sciatica_16 laceration_5
             laceration_10 jealousy_11 boils_12 anxiety_13 dread_14 boils_30
             grief_31 loneliness_32 hangover_9 abrasion_29 - pain
)
   (:init
(= (locale apple) 0)
          (eats wurst lemon)
          (craves prostatitis_7 snickers)
(= (harmony love) 2)
          (craves sciatica wurst)
          (eats snickers wurst)
          (eats wurst snickers)
          (eats popover hamburger)
          (craves hangover lemon)
          (eats popover snickers)
          (eats guava marzipan)
          (craves anger flounder)
          (eats okra hamburger)
          (craves hangover_3 okra)
(= (harmony expectation) 2)
          (eats apple snickers)
          (craves angina flounder)
          (craves anger_4 okra)
          (eats wurst muffin)
          (eats lemon muffin)
          (craves boils_12 popover)
          (eats flounder wurst)
(= (harmony rest) 1)
          (craves laceration_10 popover)

          (eats onion guava)
          (eats apple flounder)
(= (locale snickers) 2)
(= (harmony learning) 3)
          (craves boils apple)
          (craves angina_1 okra)
(= (locale muffin) 0)
          (craves jealousy muffin)
          (craves loneliness_32 hamburger)
          (craves expectation okra)
          (craves triumph apple)
          (eats okra onion)
          (craves rest guava)
          (craves depression_8 okra)
          (craves prostatitis muffin)
          (eats wurst flounder)
(= (locale marzipan) 1)
          (craves anxiety_13 popover)
          (craves depression lemon)
          (craves satisfaction muffin)
          (craves laceration apple)
          (eats hamburger popover)
          (craves dread_14 popover)
          (eats lemon wurst)
(= (harmony triumph) 2)

(= (locale hamburger) 1)
          (eats apple lemon)
          (eats flounder apple)
          (craves laceration_5 marzipan)
(= (locale onion) 0)
          (craves abrasion muffin)
          (craves loneliness wurst)
          (craves loneliness_15 marzipan)
          (eats muffin wurst)
          (eats onion okra)
          (craves grief_31 hamburger)
          (eats marzipan guava)
          (eats snickers apple)
          (craves love flounder)
          (craves abrasion_6 onion)
          (craves jealousy_11 popover)
(= (locale popover) 2)
          (eats snickers marzipan)
(= (harmony satisfaction) 3)
          (craves learning lemon)
          (craves grief muffin)


(= (locale wurst) 0)
          (eats hamburger okra)
          (eats lemon apple)
          (eats marzipan snickers)
(= (locale guava) 1)
          (craves boils_30 hamburger)
          (eats snickers popover)
(= (locale okra) 2)
          (eats muffin lemon)
(= (locale flounder) 1)
          (craves dread muffin)
(= (locale lemon) 1)
          (eats guava onion)
          (craves anxiety apple)
          (craves hangover_9 hamburger)
          (craves sciatica_16 marzipan)
          (craves grief_2 wurst)

          (craves abrasion_29 guava))
   (:goal (and (craves sciatica apple))))
