(define (problem mprime-x-13)
   (:domain mystery-prime-typed)
   (:objects lettuce chocolate mutton marzipan scallop yogurt rice
             haroset muffin potato turkey ham onion melon wurst flounder
             baguette scallion hamburger papaya lobster lemon - food
             entertainment intoxication satisfaction achievement curiosity love
             aesthetics - pleasure
             anger jealousy hangover grief abrasion loneliness anxiety
             boils sciatica dread angina laceration depression grief_1
             anxiety_2 prostatitis laceration_7 jealousy_8 boils_3 dread_4
             angina_14 hangover_15 sciatica_16 depression_5 anger_6
             loneliness_11 abrasion_12 prostatitis_13 anxiety_9 sciatica_10
             loneliness_32 prostatitis_29 laceration_30 hangover_31 dread_24
             grief_25 abrasion_26 boils_27 depression_28 anger_21
             jealousy_22 angina_23 loneliness_17 prostatitis_18
             depression_19 laceration_20 - pain
)
   (:init
(craves depression rice)
          (craves dread rice)
          (craves prostatitis_18 lemon)
(= (locale melon) 1)
          (eats lobster marzipan)
          (craves laceration_7 potato)
          (craves loneliness_32 flounder)
          (eats marzipan lobster)
(= (locale ham) 0)
          (craves anger mutton)
          (craves satisfaction rice)
          (eats rice lettuce)
(= (locale marzipan) 0)
          (eats lobster baguette)
          (eats turkey potato)
          (eats wurst ham)
          (eats mutton marzipan)
          (craves achievement turkey)
          (eats baguette lobster)
          (eats papaya hamburger)
(= (locale chocolate) 2)
          (craves sciatica_16 turkey)
          (eats baguette lemon)
          (craves abrasion_26 scallion)
(= (locale baguette) 2)
          (eats hamburger papaya)
          (eats scallop turkey)

          (eats marzipan mutton)
(= (locale yogurt) 1)
          (craves prostatitis_29 baguette)
          (craves grief_1 muffin)
          (craves laceration_30 baguette)
          (craves jealousy_8 potato)
(= (harmony love) 3)
          (eats flounder scallion)
          (craves dread_24 scallion)
          (craves intoxication yogurt)
          (craves boils_27 scallion)
(= (locale lemon) 3)

          (craves loneliness scallop)
          (eats hamburger scallion)
(= (locale muffin) 2)
(= (locale scallop) 0)
          (eats haroset wurst)
          (eats turkey onion)
(= (harmony curiosity) 2)
          (craves grief_25 scallion)
          (eats melon haroset)
          (eats flounder lemon)
(= (harmony satisfaction) 1)
          (craves entertainment mutton)
          (craves abrasion scallop)
          (eats potato muffin)
          (craves hangover_31 baguette)
          (eats lettuce rice)
          (eats turkey scallop)
          (eats lettuce chocolate)
          (craves grief scallop)
          (craves aesthetics hamburger)
          (eats lemon onion)
          (eats yogurt scallop)
          (eats lemon flounder)
          (eats chocolate lettuce)
(= (locale onion) 1)
          (eats onion lemon)
          (eats haroset melon)
          (craves love baguette)
(= (harmony intoxication) 2)
(= (locale flounder) 3)
          (craves curiosity ham)
(= (locale wurst) 2)
          (craves abrasion_12 ham)
          (craves dread_4 potato)
          (eats mutton scallop)
          (craves hangover scallop)
(= (locale turkey) 2)
          (eats rice marzipan)
          (craves anxiety_9 melon)
          (craves laceration rice)
          (craves anger_6 turkey)
          (eats scallion flounder)
(= (locale potato) 1)
(= (harmony achievement) 3)
          (craves jealousy marzipan)
          (craves prostatitis_13 ham)
(= (locale lobster) 1)
          (eats muffin ham)
          (craves depression_28 scallion)
          (craves angina_23 hamburger)
          (craves sciatica rice)
          (craves boils yogurt)
          (eats scallop yogurt)
(= (locale rice) 3)
          (eats papaya lobster)



          (craves laceration_20 lemon)
          (craves boils_3 potato)
          (craves loneliness_11 ham)
          (craves jealousy_22 hamburger)
          (craves anxiety yogurt)
(= (locale mutton) 3)
          (craves hangover_15 turkey)
          (eats yogurt chocolate)
          (craves angina rice)
          (eats ham muffin)
          (eats scallop mutton)
(= (locale lettuce) 1)
          (eats onion melon)
          (eats ham wurst)
          (eats chocolate yogurt)
          (eats wurst haroset)
          (eats potato turkey)
(= (locale scallion) 1)
          (craves depression_5 turkey)
          (craves prostatitis muffin)
(= (harmony entertainment) 3)
          (craves depression_19 lemon)
(= (locale papaya) 2)
          (eats melon onion)
          (craves anger_21 hamburger)
          (eats onion turkey)
          (eats muffin potato)
(= (locale hamburger) 2)
          (craves angina_14 turkey)
          (eats lobster papaya)
          (eats marzipan rice)
(= (locale haroset) 0)
          (craves loneliness_17 lemon)
(= (harmony aesthetics) 1)

          (craves anxiety_2 muffin)
          (eats scallion hamburger)
          (craves sciatica_10 melon)
          (eats lemon baguette))
   (:goal (and (craves prostatitis_18 lobster)
               (craves laceration_20 ham))))
