@startuml schema2
hide footbox
skinparam sequenceMessageSpacing 3
skinparam ParticipantPadding 40

actor Utente as U
participant "posthoc-app" as App #lightgreen
participant "jpddlplus" as Jpddl #orange

loop Esecuzione
U -> Jpddl: Esegue l'istanza impostando i parametri necessari
Jpddl --> Jpddl: Salva risultato su file
U -> App: Seleziona il file da visualizzare
App --> U: Mostra l'albero di ricerca

end
@enduml
